Lambda-School-Labs/forest-fire-watch-fe

fireflight/package-lock.json
fireflight/src/components/Navigation.jsx

- [ X ] New feature (non-breaking change which adds functionality)
- [ X ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code
- [ X ] My changes generate no new warnings
- [ X ] There are no merge conflicts

Basic styling

---

fireflight/src/components/Login.jsx

Styled the login form to make it easier to use for testing.
- [ X ] New feature (non-breaking change which adds functionality)
- [ X ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code
- [ X ] There are no merge conflicts

did some basic styling for the login form

---

fireflight/src/components/Login.jsx
fireflight/src/components/Register.jsx

Added some basic styling to the registration page so it can more easily be used for testing.
Styling
- [ X ] New feature (non-breaking change which adds functionality)
- [ X ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code
- [ X ] My changes generate no new warnings
- [ X ] There are no merge conflicts

Styling register

---

fireflight/src/App.js
fireflight/src/components/AuthForms/Combine.js
fireflight/src/components/AuthForms/Login.jsx
fireflight/src/components/AuthForms/Register.jsx
fireflight/src/components/Modal/Modal.js
fireflight/src/components/Navigation.jsx
fireflight/src/context/GlobalContext.jsx
fireflight/src/context/types.js

working on doing the design for the auth forms.
- [ X  ] New feature (non-breaking change which adds functionality) 
- [ X  ] I have performed a self-review of my own code
- [ X ] I have commented my code, particularly in hard-to-understand areas
- [ X  ] There are no merge conflicts

Auth forms design

---

fireflight/src/App.js
fireflight/src/components/AuthForms/AuthForms.jsx
fireflight/src/components/AuthForms/Combine.jsx
fireflight/src/components/AuthForms/Login.jsx
fireflight/src/components/AuthForms/LoginSplit.jsx
fireflight/src/components/AuthForms/Register.jsx
fireflight/src/components/AuthForms/RegisterSplit.jsx
fireflight/src/components/Modal/Modal.jsx
fireflight/src/components/Navigation.jsx
fireflight/src/context/GlobalContext.jsx
fireflight/src/context/contextProvider.js

Trying to improve the structure of context API
- [ X ] New feature (non-breaking change which adds functionality)
- [ X ] I have performed a self-review of my own code
- [ X ] New and existing unit tests pass locally with my changes
- [ X ] There are no merge conflicts

Working on context api

---

fireflight/src/components/Address.jsx
fireflight/src/context/AddressContext.jsx
fireflight/src/context/addressContextProvider.js
fireflight/src/helpers/connects.js

WIP: Radius Addition

---

fireflight/src/components/Map.jsx
fireflight/src/context/MapContext.jsx
fireflight/src/context/types.js

fire data is displaying on the map

---

fireflight/src/App.js
fireflight/src/components/AuthForms/AuthForms.jsx
fireflight/src/components/Dashboard.jsx
fireflight/src/components/Home.jsx
fireflight/src/components/Navigation.jsx
fireflight/src/components/PrivateMap.jsx
fireflight/src/components/PublicMap.jsx
fireflight/src/context/PublicMapContext.jsx

Adds the public map to the home screen
added feature

Public map

---

fireflight/src/components/Address.jsx

Sometimes, user's address will change to programmers

wip: fix that others are having issues with

---

fireflight/src/App.js
fireflight/src/components/AuthForms/Register.jsx
fireflight/src/components/Navigation.jsx
fireflight/src/components/PrivateMap.jsx
fireflight/src/utils/axiosWithAuth.js

Maps are displaying but fire data is still not working properly.

Connect map backend

---

fireflight/src/context/MapContext.jsx
fireflight/src/utils/axiosWithAuth.js

axiosWithAuth URL now depends on environment

---

fireflight/public/_redirects
fireflight/src/App.js
fireflight/src/components/Address.jsx
fireflight/src/components/Navigation.jsx
fireflight/src/context/AddressContext.jsx
fireflight/src/helpers/connects.js

MVP: Update

---

fireflight/src/components/Address.jsx
fireflight/src/context/AddressContext.jsx

Bug Fix, duplicating addresses on initial load

Addtional fields

---

fireflight/src/App.js

fixed alerts bug

---

fireflight/src/App.js
fireflight/src/components/AlertsContainer.jsx

fixing alerts

---

fireflight/public/index.html

Added google analytics tag to app

added google analytics tag

---

fireflight/yarn.lock

fixed a security vulnerability with ESM

---

fireflight/src/components/PublicMap.jsx
fireflight/src/styles/_buttons.scss
fireflight/src/styles/_forms.scss
fireflight/src/styles/_mobile.scss

Small tweaks to auth form input sizes for spacing between icons

---

fireflight/src/components/AuthForms/Login.jsx
fireflight/src/components/Navigation.jsx
fireflight/src/components/PublicMap.jsx
fireflight/src/styles/_forms.scss
fireflight/src/styles/_mobile.scss

Profile styles

---

fireflight/src/styles/_mobile.scss

Alright one last time. Mobile view SHOULD be good.

---

fireflight/src/components/Address.jsx
fireflight/src/components/Navigation.jsx
fireflight/src/styles/App.scss
fireflight/src/styles/_buttons.scss
fireflight/src/styles/_forms.scss
fireflight/src/styles/_mobile.scss
fireflight/src/styles/_model-splits.scss
fireflight/src/styles/_navigation.scss
fireflight/src/styles/_vars.scss

reformatted scss for better readability

---

fireflight/src/components/Dashboard.jsx
fireflight/src/components/PublicMap.jsx
fireflight/src/context/UserDataContext.jsx

saved locations are being rendered in profile page

Mike profile page

---

fireflight/src/components/PublicMap.jsx
fireflight/src/subscriptions.js

map style test

---

fireflight/src/components/Dashboard.jsx
fireflight/src/context/UserDataContext.jsx

fixed bug with phone input not displaying properly

---

fireflight/src/context/UserDataContext.jsx

fixing phone number bug

---

fireflight/package-lock.json
fireflight/src/components/AuthForms/Login.jsx
fireflight/src/components/AuthForms/Register.jsx
fireflight/src/styles/App.scss
fireflight/src/styles/_auth-forms.scss
fireflight/src/styles/_forms.scss
fireflight/src/styles/_mobile.scss
fireflight/src/subscriptions.js

Auth alerts

---

fireflight/src/components/PrivateMap.jsx

removing a private key

---

fireflight/src/components/Dashboard.jsx
fireflight/src/components/PublicMap.jsx
fireflight/src/context/UserDataContext.jsx

Added in functionality to trigger push notifications from profile page

tied in push notification trigger to toggle switch

---

fireflight/src/components/Dashboard.jsx
fireflight/src/context/UserDataContext.jsx
fireflight/src/styles/_auth-forms.scss
fireflight/src/styles/_buttons.scss

Push trigger

---

fireflight/src/components/Dashboard.jsx
fireflight/src/subscriptions.js

push notification bug finding

---

fireflight/src/components/MapLegend.jsx

did some minormap legend styling

---

fireflight/src/context/FireDataContext.jsx

adjusted exclamation marks to new fire icon size

---

fireflight/src/styles/_navigation.scss
fireflight/src/subscriptions.js

Nav styles

---

fireflight/src/App.js
fireflight/src/components/Dashboard.jsx
fireflight/src/context/FireDataContext.jsx

- added comments about previous code. changed api call url to the one DS fixed.
- updated DS endpoint

added comments to code

---

fireflight/src/App.js
fireflight/src/components/AuthForms/Login.jsx
fireflight/src/components/AuthForms/Register.jsx
fireflight/src/context/FireDataContext.jsx
fireflight/src/styles/App.scss
fireflight/src/styles/_auth-forms.scss
fireflight/src/styles/_buttons.scss
fireflight/src/styles/_login.scss
fireflight/src/styles/_model.scss
fireflight/src/styles/_register.scss
fireflight/src/styles/_vars.scss

Neha Modal Register and Login style updates

---

fireflight/src/App.js
fireflight/src/components/AuthForms/Login.jsx
fireflight/src/context/FireDataContext.jsx
fireflight/src/styles/App.scss
fireflight/src/styles/_auth-forms.scss
fireflight/src/styles/_buttons.scss
fireflight/src/styles/_login.scss
fireflight/src/styles/_model.scss
fireflight/src/styles/_vars.scss

updated login/registration forms. removed split functionality and hit 90% of UX design for login form. 

login form styling

---

fireflight/src/App.js
fireflight/src/components/LandingPage.jsx

added link to try it out button

---

fireflight/src/App.js
fireflight/src/components/LandingPage.jsx
fireflight/src/components/PublicMap.jsx

landing page finished and dark mode implmented

---

fireflight/src/styles/App.scss
fireflight/src/styles/_auth-forms.scss
fireflight/src/styles/_buttons.scss
fireflight/src/styles/_login.scss
fireflight/src/styles/_model.scss
fireflight/src/styles/_register.scss

btn hover effects, text input color, X button fixed

---

fireflight/src/components/MapLegend.jsx
fireflight/src/styles/App.scss
fireflight/src/styles/_map-legend.scss

styled maplegend

---

fireflight/package.json
fireflight/src/App.js
fireflight/src/components/AuthForms/Login.jsx
fireflight/src/components/AuthForms/Register.jsx
fireflight/src/components/LandingPage.jsx
fireflight/src/config/fire.js
fireflight/src/helpers/connects.js
fireflight/yarn.lock

Firebase auth on FE for login and registration working!

Np firebase auth

---

fireflight/src/helpers/connects.js

updated connects

---

fireflight/src/helpers/connects.js

put the / in the URl for the db

---

fireflight/src/config/vars.js
fireflight/src/helpers/connects.js
fireflight/src/subscriptions.js
fireflight/src/utils/axiosWithAuth.js

made all vars exportable

---

fireflight/src/helpers/connects.js

fixed minor bug

---

fireflight/src/config/vars.js
fireflight/src/helpers/connects.js
fireflight/src/subscriptions.js

minor changes

---

fireflight/src/helpers/connects.js

small tiny mistake

---

fireflight/src/components/Navigation.jsx

Edited the code so the menu will always be toggled on any size view. previously it was disappearing in mobile view with a missing toggle button.

Menu always toggled on

---

fireflight/src/components/AuthForms/Login.jsx
fireflight/src/components/AuthForms/Register.jsx
fireflight/src/components/PublicMap.jsx
fireflight/src/config/vars.js
fireflight/src/helpers/connects.js
fireflight/src/styles/_auth-forms.scss
fireflight/src/styles/_buttons.scss
fireflight/src/styles/_login.scss
fireflight/src/styles/_mobile.scss
fireflight/src/styles/_navigation.scss
fireflight/src/styles/_vars.scss
fireflight/src/subscriptions.js
fireflight/src/utils/axiosWithAuth.js

map resizing on browser resize

---

fireflight/src/helpers/connects.js

comment out production if statement

---

fireflight/src/config/vars.js
fireflight/src/helpers/connects.js
netlify.toml

Used REACT_APP_ENV to set base url depending on environment

Fixed environment variable (references url)

---

fireflight/src/styles/_forms.scss
fireflight/src/styles/_navigation.scss

Fixes #navbar hover fix. (issue)

Db styling refactoring

---

fireflight/src/components/Navigation.jsx
fireflight/src/styles/_navigation.scss

fixing Navbar padding issues

---

fireflight/src/components/Navigation.jsx
fireflight/src/styles/_navigation.scss

Fixes #Navbar in private mode (issue)

fixing Navbar in private mode

---

fireflight/src/components/Navigation.jsx

Fixes #Navbar home button (issue)

fixing Navbar Home button

---

fireflight/src/components/Navigation.jsx

fixing Home button

---

fireflight/src/styles/_navigation.scss

Fixes #Sign Up button styling (issue)

fixing Sign In button

---

fireflight/src/components/PublicMap.jsx

Fixes #privateMap Sign Up button (issue)

conditional rendering for Sign Up button

---

fireflight/src/components/AuthForms/Login.jsx
fireflight/src/styles/_login.scss

Changed bg-color on modal crosslinks

---

fireflight/src/styles/_buttons.scss
fireflight/src/styles/_forms.scss
fireflight/src/styles/_login.scss
fireflight/src/styles/_map-legend.scss
fireflight/src/styles/_navigation.scss
fireflight/src/styles/_register.scss

Fixes #mobile view issues (issue)

fixed mobile view issues

---

fireflight/src/components/AuthForms/Combine.jsx
fireflight/src/components/AuthForms/Password.jsx

Fixed modal where "forgot password?" wasn't toggling. Now all three auth modals are linked up and working. Forgot password functionality not hooked up yet through firebase.

Modal Fixes

---

fireflight/src/components/AuthForms/Combine.jsx
fireflight/src/components/AuthForms/Password.jsx
fireflight/src/components/PublicMap.jsx

Signup button on map now opens the registration modal

Np signup btn

---

fireflight/src/components/AuthForms/Login.jsx
fireflight/src/components/AuthForms/Password.jsx
fireflight/src/components/AuthForms/Register.jsx
fireflight/src/styles/App.scss
fireflight/src/styles/_login.scss
fireflight/src/styles/_password.scss

Tested forgot password functionality and fixed modal styling.

tested forgot password functionality and fixed styling on modals.

---

fireflight/src/components/AuthForms/AuthForms.jsx
fireflight/src/components/AuthForms/Login.jsx
fireflight/src/components/AuthForms/Password.jsx
fireflight/src/components/AuthForms/Register.jsx
fireflight/src/styles/_auth-forms.scss
fireflight/src/styles/_dashboard.scss
fireflight/src/styles/_login.scss
fireflight/src/styles/_model.scss
fireflight/src/styles/_password.scss
fireflight/src/styles/_vars.scss

Neha and I fixed issue of password modal displaying at the bottom of login or register modals. Fixed some of the modal styling but mobile still needs work.

Login component labs17

---

fireflight/src/config/vars.js
fireflight/src/utils/axiosWithAuth.js

Updated environment variable ternary in axioswithauth

altered axiosWithAuth to include staging and production

---

fireflight/src/components/AuthForms/Password.jsx
fireflight/src/components/AuthForms/Register.jsx
fireflight/src/components/Modal.jsx

Fixed modal issue on smaller screens where it remained and blocked the nav bar functionality

Modal Bug Fix

---

fireflight/public/index.html

for some reason the favicon was looking for favicon1.svg rather the one I got from gabby. 

forced favicon change

---

fireflight/src/styles/App.scss
fireflight/src/styles/_buttons.scss
fireflight/src/styles/_forms.scss
fireflight/src/styles/_login.scss
fireflight/src/styles/_model-splits.scss
fireflight/src/styles/_model.scss

forgot password centered, breakpoints for tablet adjusted, absolute positioning removed for mobile modal

Modal styling fixes for mobile

---

fireflight/src/styles/_register.scss

removed absolute positioning for register modal so it is more responsive to mobile

register modal at mobile size fixed. got rid of absolute positioning

---

fireflight/src/components/LandingPage.jsx

added some opacity to the landing page to make it more true to UX designs. 

added opacity to the landing page.

---

fireflight/src/styles/_navigation.scss

fixed landing page to get rid of scroll bars

fixed landing page to get rid of scroll bars

---

fireflight/src/components/Dashboard.jsx
fireflight/src/components/NavigationProfile.jsx
fireflight/src/styles/App.scss
fireflight/src/styles/_dashboard.scss
fireflight/src/styles/_navigation-profile.scss
fireflight/src/styles/_navigation.scss

Fixes #desktop profile page styling (issue)

Desktop profile changes

---

fireflight/src/components/Address.jsx
fireflight/src/components/Dashboard.jsx
fireflight/src/context/FireDataContext.jsx
fireflight/src/context/UserDataContext.jsx
fireflight/src/styles/App.scss
fireflight/src/styles/_auth-forms.scss
fireflight/src/styles/_buttons.scss
fireflight/src/styles/_dashboard.scss

Removed all styled-components and unused inline styling. Added back in edit phone functionality.

Dashboard - locations update

---

fireflight/src/components/Dashboard.jsx
fireflight/src/styles/_dashboard.scss
fireflight/src/styles/_navigation-profile.scss

Resolved merge conflicts with Lily's commits, kept media queries for mobile

Profile mobile version changes

---

fireflight/package.json
fireflight/src/components/PublicMap.jsx
fireflight/src/styles/_forms.scss
fireflight/yarn.lock

Autocomplete functionality added to the search bar!

Autocomplete map

---

fireflight/src/components/Dashboard.jsx
fireflight/src/styles/_dashboard.scss

Styled "add phone number" button, fixed issue with horizontal scroll bar, fixed toggle by adding className

Np profile mobile view

---

fireflight/package.json
fireflight/src/App.js
fireflight/src/components/Dashboard.jsx
fireflight/src/styles/_dashboard.scss
fireflight/yarn.lock

Added an icon and conditional rendering to support the edit email button, and make the axios request. Backend now supports the update in the DB, just need to fix a small issue where after the user submits the new email and reverts back to the email text it still shows the old email. 

Edit email

---

fireflight/package.json
fireflight/src/App.js
fireflight/src/components/AuthForms/Register.jsx
fireflight/src/components/Dashboard.jsx
fireflight/src/styles/_dashboard.scss
fireflight/yarn.lock

user will no longer register with firebase even if there is an error in the form. There has to be a better way to have done this but this a brute force implementation. 

Input check before

---

fireflight/src/App.js
fireflight/src/components/Address2.jsx
fireflight/src/components/AuthForms/Login.jsx
fireflight/src/components/Dashboard.jsx
fireflight/src/components/PublicMap.jsx
fireflight/src/context/FireDataContext.jsx
fireflight/src/styles/_address2.scss
fireflight/src/styles/_dashboard.scss

Fixes #functionality of add location page in progress. (issue)

Add location page

---

fireflight/src/App.js
fireflight/src/components/Dashboard.jsx
fireflight/src/styles/_dashboard.scss

Fixes #changes from Alex branch. (issue)

Edit email functionality

---

fireflight/src/components/Dashboard.jsx

Users are now not able to toggle the notification button without having a phone number provided. 

phone must be filled in before notification toggle

---

fireflight/src/components/Dashboard.jsx
fireflight/src/styles/_dashboard.scss

adding scss that wont go in

---

fireflight/src/components/Dashboard.jsx

changed icon to button

---

fireflight/src/components/AuthForms/AuthForms.jsx
fireflight/src/components/AuthForms/Register.jsx
fireflight/src/components/PublicMap.jsx

Co-authored-by: Neha Patel <neha.r.p@gmail.com>
Fixed multiple modal bugs and restyled saved location pin modal to match UX

Bug Fixes and Pin Modals

---

fireflight/src/components/PublicMap.jsx
fireflight/src/context/FireDataContext.jsx

Fixes #deletes the pin. (issue)

delete pin functionality 

---

fireflight/src/components/Address.jsx
fireflight/src/components/AuthForms/Login.jsx
fireflight/src/components/AuthForms/Password.jsx
fireflight/src/components/Dashboard.jsx
fireflight/src/components/PublicMap.jsx
fireflight/src/context/FireDataContext.jsx
fireflight/src/context/UserDataContext.jsx
fireflight/src/helpers/connects.js
fireflight/src/subscriptions.js

Fixes #first name and last name on Profile fixed, and Console errors cleanup (issue)

First name and last name on Profile fixed, Console errors cleanup

---

fireflight/src/components/NavigationProfile.jsx
fireflight/src/helpers/connects.js
fireflight/src/utils/axiosWithAuth.js

changed REACT_APP_ENV

---

fireflight/src/context/UserDataContext.jsx
fireflight/src/subscriptions.js

Fixes #push notifications (issue)

new VAPID keys

---

fireflight/src/components/PublicMap.jsx

reset radius input after search for address, on both pop-up of location and main search bar

Reset inputs after submit

---

fireflight/src/styles/_buttons.scss
fireflight/src/styles/_forms.scss

the sign up button no longer overlays the legend on mobile, clearing up the UI significantly 

fixed the sign up button on mobile to no longer display.

---

fireflight/src/components/Dashboard.jsx

removed link and used history prop instead to navigate user to form

---

fireflight/src/components/Dashboard.jsx
fireflight/src/utils/haversineDistance.js

removed react_app_env from change email put request

---

fireflight/src/components/PublicMap.jsx

Adding two lines of code that were previously missing to store address and radius in local storage

Testing labs17

---

fireflight/src/components/Dashboard/index.jsx
fireflight/src/context/FireDataContext.jsx
fireflight/src/context/UserDataContext.jsx

Make sure users only get alerts when they toggle for specific things

Make sure users only get alerts when they toggle for specific things

---

fireflight/src/components/Dashboard/index.jsx
fireflight/src/context/UserDataContext.jsx

Fix phone number state loading / saving

Fix phone number state loading / saving

---

fireflight/src/context/UserDataContext.jsx

added back getSub function

---

fireflight/src/components/Dashboard/index.jsx

push toggle

---

fireflight/src/components/PublicMap.jsx

all fixed, passed the viewport when setting the viewport.

fixed the white screen issue

---

fireflight/src/context/UserDataContext.jsx

Fixes # push only triggering on toggle on

push only triggering on toggle on

---

fireflight/src/components/Dashboard/LocationsList.jsx
fireflight/src/components/Dashboard/index.jsx

Fixes # alerts ON and OFF pulls the data from state

alerts ON and OFF pulls the data from state

---

fireflight/src/styles/App.scss
fireflight/src/styles/_address-form.scss
fireflight/src/styles/_navigation-profile.scss

Fixed the mobile view of Address component## Type of change

fixed the mobile view of Address component

---

fireflight/src/components/AuthForms/Login.jsx

got backend text to render as red error on front end for 403/user not found
-  [x] New feature (non-breaking change which adds functionality)

error showing on form

---

fireflight/src/styles/_navigation-profile.scss

Fixes #  styling of NavigationProfile and logout

fixed styling of NavigationProfile and logout

---

fireflight/src/components/PublicMap.jsx
fireflight/src/styles/_navigation-profile.scss

fixing radius

---

fireflight/src/components/PublicMap.jsx
fireflight/src/styles/_navigation-profile.scss

fixing radius default

---

fireflight/src/subscriptions.js

fixed env variable for push

---

fireflight/src/components/PublicMap.jsx
fireflight/src/subscriptions.js

Fixed ENV Vars for push

---

fireflight/src/serviceWorker.js

Fixes env variables for serviceWorker

fixing env variables for serviceWorker

---

fireflight/src/serviceWorker.js
fireflight/src/subscriptions.js

Changed SW env vars 

---

fireflight/src/subscriptions.js

fixing push on master branch

---

fireflight/src/components/PublicMap.jsx

added useEffect to setViewport

---

fireflight/src/components/PublicMap.jsx

fixing bug

---

fireflight/src/components/PublicMap.jsx

changed the zoom

---

fireflight/public/index.html
fireflight/src/components/AuthForms/Login.jsx
fireflight/src/components/AuthForms/Password.jsx
fireflight/src/components/AuthForms/Register.jsx
fireflight/src/components/PublicMap.jsx
fireflight/src/styles/Forms.jsx

changed the error text size as well as add logic for forgot password

Error text

---

fireflight/public/index.html
fireflight/src/components/PublicMap.jsx

if the user grants the permission to have access to location, the map with reset the viewport to those lat and longs, otherwise will reset viewport to IP location coords, otherwise will set viewport to entire United states. 

GeolocateControl fully functional and resetting viewport. 

---

fireflight/src/components/LandingPage.jsx
fireflight/src/components/PublicMap.jsx
fireflight/src/styles/Forms.jsx
fireflight/src/styles/_buttons.scss
fireflight/src/styles/_forms.scss
fireflight/src/styles/_login.scss
fireflight/src/styles/_map-legend.scss
fireflight/src/styles/_model.scss
fireflight/src/styles/_navigation.scss
fireflight/src/styles/_password.scss
fireflight/src/styles/_register.scss

Fix map mobile view

---

fireflight/src/styles/_forms.scss

fix z-index for input field

---

fireflight/src/styles/_buttons.scss
fireflight/src/styles/_forms.scss
fireflight/src/styles/_map-legend.scss

 fixing geocoder

---

fireflight/src/components/PublicMap.jsx

adding back width and height

---

fireflight/public/manifest.json

edited file type

---

fireflight/src/styles/App.scss
fireflight/src/styles/_address-form.scss
fireflight/src/styles/_forms.scss
fireflight/src/styles/_navigation-profile.scss

Fixes add Location mobile styling

Add Location mobile styling

---

fireflight/public/manifest.json

trying this last thing

---

README.md
fireflight/src/utils/axiosWithAuth.js

env vars description and clean up axioswithauth

env vars and clean up axioswithauth

---

README.md

mobile description

---

fireflight/src/components/PublicMap.jsx

Geocoder fix

---

fireflight/src/components/Dashboard/LocationsList.jsx
fireflight/src/styles/_dashboard.scss

Added Return To Map button on the Profile page to give user the ability to quickly/easily get "home"

Added Return To Map button.

---

fireflight/src/styles/_model.scss

centered login and sign up modal for desktop and mobile

---

fireflight/src/components/Checklist.jsx
fireflight/src/components/Dashboard/index.jsx
fireflight/src/components/HamburgerNavigation.jsx
fireflight/src/styles/App.scss
fireflight/src/styles/_checklist.scss
fireflight/src/styles/_dashboard.scss

Updated logic in checklist component to save checked items in local storage, also added a return to map button to the checklist component

Profile address
